### ISSUE TITLE
Redesign Lint Warning Icon in Editor 

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vizhub-feedback#515]
Yellow Icon needs redesign, too big and bright, I think.
![errorIcon](https://user-images.githubusercontent.com/13540669/96769931-d5131680-13ad-11eb-8bef-248579de4aa6.png)

**Comment by curran** [comment]
Oh yes for sure! Was thinking to include this in the icon redesign work across the platform.

We're just using the default for now, whatever came from the CodeMirror example.

Definitely want to iterate on this icon design.

**Comment by nitanagdeote** [comment]
I was thinking something like this, just an idea 
https://www.figma.com/file/x4kCD3rhkCBrRC9PJhyZIe/error-icon-design?node-id=3%3A13

**Comment by curran** [comment]
Cool idea!

![image](https://user-images.githubusercontent.com/68416/96927534-2fcb7180-1485-11eb-880c-83a97c65e7c8.png)

**Comment by curran** [comment]
This is done!

![image](https://github.com/vizhub-core/vizhub-feedback/assets/68416/7525f267-7cce-417d-903f-4b19183c2c74)
