### ISSUE TITLE
Not forked icon

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vizhub-feedback#519]
WIP
https://www.figma.com/file/bbUmP4DRMv8ri3GJbCtOlu/Not-Forked-Icon?node-id=0%3A1

**Comment by curran** [comment]
![image](https://user-images.githubusercontent.com/68416/118377730-19aa0d80-b59d-11eb-8f34-cc8cb791c7f1.png)

@nitanagdeote Was there a different not forked icon? This is where that link goes. Thanks!
