### ISSUE TITLE
Log In Bug

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vizhub-feedback#530]
I am already signed in, still shows not signed in.
![logInError](https://user-images.githubusercontent.com/13540669/96929797-bdf52700-1488-11eb-9543-64881a805fc9.png)

**Comment by curran** [comment]
Hmmm... Needs investigation. How to reproduce this?

I tried to reproduce. Here's what I see when I'm not logged in and try to edit someone else's viz:

![image](https://user-images.githubusercontent.com/68416/97692536-47eb5400-1a76-11eb-877d-c5fb26ac6f34.png)

Here's what I see when I log in and try to edit someone else's viz:

![image](https://user-images.githubusercontent.com/68416/97692602-5df91480-1a76-11eb-8ae6-9a81e8337bd4.png)

@nitanagdeote How did you get it to show like in that screenshot?
