### ISSUE TITLE
"Upvote Icon" change to gold star

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vizhub-feedback#566]
![Group 2star](https://user-images.githubusercontent.com/13540669/99312894-b6793180-282c-11eb-842a-f85fa7c1f1d3.jpg)

**Comment by stushurik** [comment]
@nitanagdeote how it should look like if lets say 10 users upvote the viz?

**Comment by curran** [comment]
I'm open to change the upvote icon to something else. It should be thought-through thoroughly though.

Some options:
 * Star
 * Heart
 * Clap
 * Like (thumbs up)

I think the substance of the feature will not change - it will still be "upvoting" essentially - but sure, maybe the up arrow icon is not the best choice. Open to change it indeed.

We can research what other sites have done and compile a list.

Another related idea - downvote. I think I would like to introduce downvoting at some point. I think Reddit has this. Also YouTube has a "thumbs down".

**Comment by nitanagdeote** [comment]
> @nitanagdeote how it should look like if lets say 10 users upvote the viz?

I just didn't think about that!

**Comment by nitanagdeote** [comment]
Maybe we can put a number inside the star

**Comment by stushurik** [comment]
@curran not sure that downvote is a good idea for vizhub. user put some efforts (maybe a lot of efforts) creating a viz so its not correct blame such user. Maybe if user posts inappropriate content would be better to provide other user mark such with as inappropriate

**Comment by curran** [comment]
GitHub's design:

![image](https://user-images.githubusercontent.com/68416/100659382-8f3b5d80-331e-11eb-9d2f-d1118d95f918.png)

YouTube's design:

![image](https://user-images.githubusercontent.com/68416/100659418-9bbfb600-331e-11eb-8cb4-d36ee04997b1.png)

Medium's design:

![image](https://user-images.githubusercontent.com/68416/100659468-abd79580-331e-11eb-8e2b-dc9fe3dfafd3.png)

VizHub's design (could replace arrow with star and keep the number):

![image](https://user-images.githubusercontent.com/68416/100659534-c3af1980-331e-11eb-9aa9-89fde9fde57b.png)

**Comment by curran** [comment]
@stushurik Re: downvote - it is a bit sensitive, which is why it has not been introduced yet. The main use case I can see it useful for is flagging abuse on the platform. Maybe downvote is not the right thing for that, though. There could be another separate thing, maybe "report abuse" or "mark as inappropriate".

**Comment by stushurik** [comment]
@curran i think would better add explicit link or button for flagging abuse instead of downvote

**Comment by curran** [comment]
This is done!

![image](https://github.com/vizhub-core/vizhub-feedback/assets/68416/bbe92095-6d61-4bca-a47a-1162a8095167)
