### ISSUE TITLE
Add link from viz too large to fork error into blog post.

### ISSUE THREAD

**Issue by curran** [vizhub-core/vizhub-feedback#576]
https://vizhub.com/blog/2020/11/13/vizhub-error-this-viz-is-too-large-to-fork/

**Comment by curran** [comment]
For now a link that says "Learn more"

**Comment by stushurik** [comment]
@curran I think https://github.com/datavis-tech/vizhub-issue-tracker/projects/2#card-49334043 can be deleted as duplicate

**Comment by curran** [comment]
Good call. Done!
