### ISSUE TITLE
Revise Create-Viz Page

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vizhub-feedback#646]
https://vizhub.com/nitanagdeote/87d7b6c6b28a40c6a547006740fb59c9?edit=files&file=index.html&line

**Comment by curran** [comment]
Yeah we need all new templates for 2020. I've been thinking about this a lot actually.

Some general ideas:
 * The new templates should use the new `package.json` feature.
 * The new templates should be ISC Licensed, to match with the most common license in Obseravble content.

Ideas for templates to release:
 * D3 Template
 * React Template
 * D3 + React template (with demonstration of `useRef`-based integration)
 * Svelte template

Template sections for existing old vizzes:
 * Datavis 2020 pieces
 * Dataviz Course 2018 Pieces
 * Most Forked
 * Most Upvoted
