### ISSUE TITLE
Support deletion of index.html

### ISSUE THREAD

**Issue by curran** [vizhub-core/vizhub-feedback#66]
As a visualization author I want be stopped from deleting index.html, so that I don't accidentally break the visualization completely.

Please :+1: this issue to help prioritize this task in our [backlog](https://github.com/datavis-tech/vizhub-ui/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by curran** [comment]
Might do this already - needs verification.

**Comment by stushurik** [comment]
@curran is this still relevant?

**Comment by curran** [comment]
Yes. Verified that currently it is possible to delete `index.html`, which breaks the viz.

**Comment by curran** [comment]
Deletion of index.html is an opportunity for VizHub to provide a _better_ experience that is different from what it normally does.

If index.html is deleted, we have a lot more control over what HTML gets executed and how updates happen.

I'd like to make it so that when you delete index.html, the VizHub runtime has unique behavior that supports:
 * Hot module reloading for CSS and JS
 * Externalized application state (#310 , #165 )
 * Import from other vizzes (#81 )
