### ISSUE TITLE
Mark Viz as Prototype

### ISSUE THREAD

**Issue by ghost** [vizhub-core/vizhub-feedback#682]
This is a proposed idea that, I believe, might solve #618 and related issues...
A feature in which users mark their viz as a prototype. This affects the viz in two ways:

1. Prevent the viz from appearing at all in the VizHub home page.
2. Prototypes are gathered in a section at the bottom of the page, separate from the "complete" projects.

Again, the feature is primarily intended to improve organization of the home page and individual profile pages.

**Comment by curran** [comment]
Very cool idea!

I feels similar to GitHub's feature of a "Draft" Pull Request.

Also sort of similar to Unlisted concept #243 .

Thanks for sharing this idea!

**Comment by waseem-medhat** [comment]
True. It is similar to the unlisted concept, although the way I imagined it prototypes are brought down in the profile but not hidden completely.

Also, another way it could be valuable in terms of "fixing" the home page is that you could add the "Mark as prototype" checkbox in the forking dialog, which is checked by default. That should encourage a best practice of sorts where the viz I start working on is hidden from the home page by default, and I un-mark it when it is ready to be public.

**Comment by curran** [comment]
Interesting. So, in a way, it's the "opposite" of [pinning](https://github.com/datavis-tech/vizhub-issue-tracker/issues/673).
