### ISSUE TITLE
Stargazers

### ISSUE THREAD

**Issue by curran** [vizhub-core/vizhub-feedback#770]
As a VizHub user, I want to know who has starred my viz.

**Comment by curran** [comment]
I wonder what the UI should be like...

Here's what Discord does:

![image](https://github.com/vizhub-core/vizhub-feedback/assets/68416/872ecf0c-b047-4554-a953-bd75d3bd001e)

**Comment by curran** [comment]
The GitHub UI is a whole separate section

![image](https://github.com/vizhub-core/vizhub-feedback/assets/68416/4713fc71-f290-4898-9f30-07f9c98741ef)

**Comment by higsch** [comment]
As the forks are already a separate section, I'd go for the GitHub variant.

**Comment by curran** [comment]
@higsch Thanks for the feedback! I've gone ahead and implemented that idea of stargazers as a separate section.

![image](https://github.com/vizhub-core/vizhub-feedback/assets/68416/02ae25fd-ffbf-4062-8976-6f8bc4ef5bca)

I've deployed a first version of the stargazers feature. It's rough and not linked up to the viz page yet. I'll be refining the style of it in the coming days, but it's usable now to find out who starred the viz.

Just add `/stargazers` to the URL.

For example:

https://vizhub.com/curran/be771477cb974c938cd8603dd8b59d32/stargazers

**Comment by curran** [comment]
Done!
