### ISSUE TITLE
Full screen mode for viz

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vizhub-feedback#774]
https://vizhub.com/vspatel927/a9e949d9b54a48799c0214501e3a125e?mode=embed
The image does not open in full-screen.

**Comment by curran** [comment]
The viz is full screen, but the code is not written to be responsive.

In VizHub 3, the full screen and embed mode has no automatic rescaling. It is the responsibility of the viz author to make it responsive.
